export const colorPrimary = 'var(--ew-color-primary)'
export const colorText = 'var(--ew-color-text)'
export const colorTextSecondary = 'var(--ew-color-text-secondary)'
export const colorBg = 'var(--ew-color-bg)'
export const colorBorder = 'var(--ew-color-border)'
export const colorDanger = 'var(--ew-color-danger)'

export const radiusSm = 'var(--ew-radius-sm)'
export const radiusMd = 'var(--ew-radius-md)'
export const radiusLg = 'var(--ew-radius-lg)'

export const spaceXs = 'var(--ew-space-xs)'
export const spaceSm = 'var(--ew-space-sm)'
export const spaceMd = 'var(--ew-space-md)'
export const spaceLg = 'var(--ew-space-lg)'

export const fontFamily = 'var(--ew-font-family)'
export const fontSizeSm = 'var(--ew-font-size-sm)'
export const fontSizeMd = 'var(--ew-font-size-md)'
export const fontSizeLg = 'var(--ew-font-size-lg)'
